services:
  - type: web
    name: genshin-seibutsu-checker
    env: node
    buildCommand: "apt-get update && apt-get install -y openjdk-17-jdk && ./mvnw clean install"
    startCommand: "java -jar target/*.jar"
